import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import { ThemeProvider } from '@/components/theme-provider';
import { ShootingStars } from '@/components/ui/shadcn-io/shooting-stars';
import ShootingStarAnimation from '@/components/ShootingStarAnimation';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <Header />
          <div className='flex min-h-screen items-center justify-center font-sans'>
            <main className='flex min-h-screen w-full max-w-5xl flex-col items-center justify-between py-32 px-16 sm:items-start'>
              {children}
            </main>
          </div>
          <ShootingStarAnimation />
        </ThemeProvider>
      </body>
    </html>
  );
}
